### ISSUE TITLE
Can't able to import 

### ISSUE THREAD

**Issue by nishant0131** [d0n601/All-In-One-WP-Migration-With-Import#1]
It changes the limit but not functioning. Keep giving warning "not able to import more than 512".

**Comment by d0n601** [comment]
Could you post a screen shot of the error?

**Comment by nishant0131** [comment]
![image](https://user-images.githubusercontent.com/23257562/49988961-b4eac300-ff9e-11e8-96f7-41f795ef95f1.png)

**Comment by d0n601** [comment]
I see that your file upload limit is 4GB, not 12GB, are you using the code from this repository?? If you're trying to modify the new version of the plugin from the WordPress repo, it will not work.

**Comment by nishant0131** [comment]
okay Thanks.  I am using this plugin directly from wordpress plugin directory not yours repository. I will try it from your repo.
