### ISSUE TITLE
Backups Restore

### ISSUE THREAD

**Issue by ghost** [d0n601/All-In-One-WP-Migration-With-Import#3]
Is actually a question not an issues, how do I modify the backup size limit for restorations? I was able to upload my backup via FTP but it wont allow me to restore because the plugin has a separate limitation -- 512mb max for restores. Thank you.

**Comment by d0n601** [comment]
Did you use the code from this repository, or the Wordpress plugin repo's code? The size limitation for a backup restoration is set to `32GB` by default in this GitHub repo.

**Comment by ghost** [comment]
I have your code installed and active, and I also have version 6.77 installed, not active of course. Not sure if this is affecting in some way. But yeah, I'm using your code and when hit the restore I get this:

![aiowm](https://user-images.githubusercontent.com/62854232/87735812-cbb55500-c793-11ea-9446-9a1f5570c742.png)

**Comment by ghost** [comment]
Never mind, it worked! I re-installed WordPress and used only your plugin and it worked. This was a website from a client and I've been dealing with this for 3 days. I appreciate you sharing this code, super helpful, and I think the way these people trap users into their restriction trick is very dishonest. Thanks again.

**Comment by d0n601** [comment]
Awesome glad to hear it worked  for you still!
