### ISSUE TITLE
Download Link (Original)

### ISSUE THREAD

**Issue by gknoop** [d0n601/All-In-One-WP-Migration-With-Import#5]
It would seem the developers have altered the contents of the file originally hosted at the URL for the "original" file linked at the bottom of this repo's README, so that people still wind up installing a useless version of the plugin. I'd recommend removing this link.

**Comment by d0n601** [comment]
Someone emailed me mentioning the same thing last week. When I look at the code it seems like the `constants.php` file from the 6.77 version on Wordpress.org is indeed the 6.77 constants file. However, I do see that it looks like the last modified date is in 2019 for all the files, and the README has version 7.5 listed, which isn't even out at the moment? 

Anyway, I haven't had the time to look much into it. I don't do wordpress dev anymore so I'm not setup to actually test the plugin, so I can't really say I know what's going on. I modified my readme to just link to the version control repo so people can track changes themselves.

Is it a coincidence two people mentioned this to me in the same week or is there a topic about this on a forum someplace that you can link me to?

**Comment by gknoop** [comment]
I'm not aware of any forum. I came to this realization by myself, after trying to install the zip from the URL you had linked.
